
spring.application.name=fu
spring.docker.compose.enabled=false
spring.datasource.url=jdbc:sqlite:${user.home}/.laifu/laifu.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# 將資料庫放在使用者家目錄下的隱藏資料夾 .laifu 中，這樣打包成 .app 後也能穩定找到位置
# 如果 .laifu 目錄不存在，SQLite 會自動嘗試建立檔案，但我們最好在程式中確保目錄存在。
====
====
spring.session.jdbc.initialize-schema=always
spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-sqlite.sql
server.port=0